name: Build & Push Docker to GHCR

on:
  push:
    branches: [ "main" ]  # adapte si nécessaire

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci || npm install

      - name: Build site
        run: npm run build || npm run docs:build

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: |
            ghcr.io/${{ github.repository_owner }}/vuepress-kube:latest
            ghcr.io/${{ github.repository_owner }}/vuepress-kube:${{ github.sha }}
